  jp zxengine.init

  include "src/CellType_h.asm"
  include "src/ItemType_h.asm"

  include "core/defines.asm"
  include "middlware/defines.asm"
  include "middlware/defines/Item.asm"
  include "middlware/defines/Hero.asm"
  include "middlware/defines/Vars.asm"  
  include "core/scankeys.asm"
  include "core/engine.asm"
  ; include "core/cursor.asm"
  include "core/tables.asm"
  include "core/routines/math.asm"
  include "core/routines/tiles16.asm"
  include "core/routines/view.asm"
  include "core/routines/input.asm"
  include "core/routines/zx7.a80"
  include "middlware/beeper.asm"
  include "middlware/screenfx.asm"
  include "middlware/text.asm"
  include "middlware/screen.asm"
  include "middlware/map.asm"
  include "middlware/entities.asm"
  include "middlware/items.asm"
  include "core/interrupt.asm"
